## 練習

引数に整数 $n$ を取り、$i$ から始まる連番の整数からなる配列を$i$番目 ($i\ge 0$) の行として持つ $n\times n$ の2次元配列を返す関数 `range_square_matrix()` を、`arange()` を用いて定義してください。

たとえば、`range_square_matrix(3)`は、
```
[[0 1 2]
 [1 2 3]
 [2 3 4]]
```
と印字されるような2次元配列を返します。

In [ ]:
def arange_square_matrix(n):
    ...

以下のセルを実行して、`True` が表示されることを確認してください。

In [ ]:
print(all(map(all,(arange_square_matrix(3) == np.array([[0,1,2],[1,2,3],[2,3,4]])))))

## 練習の解答

In [ ]:
def arange_square_matrix(n):
    return np.array([np.arange(i, n+i) for i in range(n)])